### ISSUE TITLE
one or two examples for me to evaluate it?

### ISSUE THREAD

**Issue by tony-teknique** [ligurio/recidive#1]
Hi I am wondering whether you could provide one or two examples for the test analyser?
Just a few command line examples will do.

**Comment by ligurio** [comment]
Hello!

```
$ git clone https://github.com/ligurio/recidive
$ cd recidive
$ go build
$ ./recidive 
2019/05/21 17:19:10 Used database db.sqlite
2019/05/21 17:19:10 Start on :8080
...
```

Then open http://127.0.0.1:8080/upload in your browser and upload some test reports (for example in JUnit format, like this https://raw.githubusercontent.com/ligurio/testres/master/samples/junit.xml).

**Comment by tony-teknique** [comment]
Thanks! @ligurio will give this a try.
